# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mapzai BETA
email: beta@mapzai.com
description: > # this means to ignore newlines until "baseurl:"
  Mapzai brings geospatial analysis to all

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://beta.mapzai.com" # the base hostname & protocol for your site
twitter_username: mapzai
github_username:  mapzai

# Build settings
markdown: kramdown
